# Generated by Django 6.0.5 on 2026-05-31 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamentos',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Motivo'),
        ),
    ]
