# Generated by Django 5.2.7 on 2025-10-20 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_consulta_cancelado_remove_consulta_confirmado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='denuncia',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='curtida',
            name='postagem',
        ),
        migrations.RemoveField(
            model_name='curtida',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='postagem',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='usuario_denunciante',
        ),
        migrations.RemoveField(
            model_name='postagem',
            name='autor',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_hora',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(limit_choices_to={'is_psicologo': False}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_paciente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='psicologo',
            field=models.ForeignKey(limit_choices_to={'is_psicologo': True}, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_psicologo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Curtida',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
        migrations.DeleteModel(
            name='Postagem',
        ),
    ]
