# Generated by Django 6.0.5 on 2026-06-07 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_agendamentos_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='terapeuta',
        ),
        migrations.AddField(
            model_name='matricula',
            name='aluno',
            field=models.OneToOneField(default=1, limit_choices_to={'is_admin_instituicao': False, 'is_psicologo': False}, on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='matricula',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matriculas_alunos', to='app.instituicao'),
        ),
    ]
