# Generated by Django 5.2.7 on 2025-10-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_denuncia_comentario_remove_curtida_postagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('agendada', 'Agendada'), ('cancelada', 'Cancelada'), ('realizada', 'Realizada')], default='pendente', max_length=20),
        ),
    ]
