# Generated by Django 6.0.5 on 2026-06-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_matricula_terapeuta_matricula_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='relatorio_clinico',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackavaliacao',
            name='nota_atendimento',
            field=models.PositiveSmallIntegerField(default=5, help_text='Nota de 1 a 5 para a sessão'),
        ),
    ]
