# Generated by Django 6.0.5 on 2026-05-31 21:06

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_psicologo', models.BooleanField(default=False)),
                ('is_admin_instituicao', models.BooleanField(default=False)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='usuarios/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_sugerida', models.DateTimeField()),
                ('status', models.CharField(choices=[('pendente', 'Aguardando Confirmação'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(limit_choices_to={'is_psicologo': False}, on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacaoConsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('analise', 'Em Análise'), ('autorizado', 'Autorizado'), ('negado', 'Negado')], default='analise', max_length=20)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(limit_choices_to={'is_psicologo': False}, on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('paciente', models.ForeignKey(limit_choices_to={'is_psicologo': False}, on_delete=django.db.models.deletion.CASCADE, related_name='chats_paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora_realizacao', models.DateTimeField()),
                ('status', models.CharField(choices=[('agendada', 'Agendada'), ('realizada', 'Realizada'), ('ausente', 'Paciente Faltou'), ('cancelada', 'Cancelada')], default='agendada', max_length=20)),
                ('observacoes_internas', models.TextField(blank=True, null=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta_vinculada', to='app.agendamentos')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_atendimento', models.PositiveSmallIntegerField(help_text='Nota de 1 a 5 para a sessão')),
                ('comentario_paciente', models.TextField(blank=True, null=True)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='app.consultas')),
            ],
        ),
        migrations.CreateModel(
            name='Formularios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Anamnese / Evolução de Caso', max_length=150)),
                ('conteudo_clinico', models.TextField(verbose_name='Prontuário/Anotações da Sessão')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios_evolucao', to='app.consultas')),
            ],
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='app.chats')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Terapeuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crp', models.CharField(max_length=20, verbose_name='Registro CRP ou de Estudante/Estagiário')),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tererapeutas', to='app.instituicao')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_terapeuta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_geral', models.TextField(help_text='Resumos estatísticos, horas de estágio acumuladas, etc.')),
                ('arquivo_pdf', models.FileField(blank=True, null=True, upload_to='relatorios/')),
                ('gerado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('terapeuta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios_gerados', to='app.terapeuta')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_matricula', models.CharField(max_length=50, unique=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.now)),
                ('ativo', models.BooleanField(default=True)),
                ('terapeuta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='matricula', to='app.terapeuta')),
            ],
        ),
        migrations.AddField(
            model_name='chats',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats_terapeuta', to='app.terapeuta'),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_terapeuta', to='app.terapeuta'),
        ),
    ]
